export const START_LOADING_SEARCH_RESULTS = 'START_LOADING_SEARCH_RESULTS';
export const END_LOADING_SEARCH_RESULTS = 'END_LOADING_SEARCH_RESULTS';
export const SET_SEARCH_RESULTS = 'SET_SEARCH_RESULTS';
